I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 830, in script
    player.fulfill "I've never hurt a soul in my life."
Exception: Sayer 'player.fulfill' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 830, in script
    player.fulfill "I've never hurt a soul in my life."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'player.fulfill' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
OrbitalWeaponsDatingSimulator 1.0
Tue Sep 19 21:12:53 2023
